using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RemotePlayer : Player {

    public Animator Animator;
    public GameObject PlayerModel;

    private float walkSpeed;
    private Vector3 lastPosition;

    public void Start()
    {
        lastPosition = transform.position;
    }

    protected override void Update()
    {
        DoAnimation();
        base.Update();
    }


    private void DoAnimation()
    {
        Vector3 dir = transform.position - lastPosition;
        lastPosition = transform.position;
        Animator.SetFloat("WalkSpeed", dir.magnitude);
        Debug.Log(dir.normalized);

        PlayerModel.transform.LookAt(PlayerModel.transform.position + dir, Vector3.up);
        //PlayerModel.transform.forward = dir.normalized;
    }
}
